### ISSUE TITLE
trigger format with formBuilder

### ISSUE THREAD

**Issue by mikehumeny** [rbalet/ngx-mat-input-tel#2]
I would like the value of the component to be formatted when initialized via formBuilder. Is this possible?
Here is my code.

.html file snippet:
      <ngx-mat-input-tel
      [ngClass]="regErr?.phone ? 'errmsg' : ''"
      [preferredCountries]="preferredCountries"
      [enablePlaceholder]="true"
      [format]="'national'"
      formControlName="phone"
      class="phoneInput"
      #phone
    >
    </ngx-mat-input-tel>

.ts file snippet:
in constructor...
    this.profileForm = this.formBuilder.group({
      phone: [this.sess.phone]
    })
![phone format](https://github.com/rbalet/ngx-mat-input-tel/assets/105063683/703c794f-85ff-4de7-a8f2-3d0553c8b915)

Is it possible to trigger the formatting of the component?

**Comment by rbalet** [comment]
@mikehumeny Sorry for the delay.

Can you give me the value from `this.sess.phone` ?

**Comment by rbalet** [comment]
@mikehumeny I'm closing the issue, feel free to open it again if needed
